// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dproto/db.proto

package dproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Just an empty message.
type DBRequest struct {
	RequestID            string   `protobuf:"bytes,1,opt,name=RequestID,proto3" json:"RequestID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBRequest) Reset()         { *m = DBRequest{} }
func (m *DBRequest) String() string { return proto.CompactTextString(m) }
func (*DBRequest) ProtoMessage()    {}
func (*DBRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db_e304bff5af2f6b9f, []int{0}
}
func (m *DBRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBRequest.Unmarshal(m, b)
}
func (m *DBRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBRequest.Marshal(b, m, deterministic)
}
func (dst *DBRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBRequest.Merge(dst, src)
}
func (m *DBRequest) XXX_Size() int {
	return xxx_messageInfo_DBRequest.Size(m)
}
func (m *DBRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DBRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DBRequest proto.InternalMessageInfo

func (m *DBRequest) GetRequestID() string {
	if m != nil {
		return m.RequestID
	}
	return ""
}

type DBObject struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Alive                bool     `protobuf:"varint,2,opt,name=Alive,proto3" json:"Alive,omitempty"`
	Addr                 string   `protobuf:"bytes,3,opt,name=Addr,proto3" json:"Addr,omitempty"`
	Removed              bool     `protobuf:"varint,10,opt,name=Removed,proto3" json:"Removed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBObject) Reset()         { *m = DBObject{} }
func (m *DBObject) String() string { return proto.CompactTextString(m) }
func (*DBObject) ProtoMessage()    {}
func (*DBObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_db_e304bff5af2f6b9f, []int{1}
}
func (m *DBObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBObject.Unmarshal(m, b)
}
func (m *DBObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBObject.Marshal(b, m, deterministic)
}
func (dst *DBObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBObject.Merge(dst, src)
}
func (m *DBObject) XXX_Size() int {
	return xxx_messageInfo_DBObject.Size(m)
}
func (m *DBObject) XXX_DiscardUnknown() {
	xxx_messageInfo_DBObject.DiscardUnknown(m)
}

var xxx_messageInfo_DBObject proto.InternalMessageInfo

func (m *DBObject) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *DBObject) GetAlive() bool {
	if m != nil {
		return m.Alive
	}
	return false
}

func (m *DBObject) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *DBObject) GetRemoved() bool {
	if m != nil {
		return m.Removed
	}
	return false
}

type DBD struct {
	ReplyID              string      `protobuf:"bytes,1,opt,name=ReplyID,proto3" json:"ReplyID,omitempty"`
	Objects              []*DBObject `protobuf:"bytes,2,rep,name=Objects,proto3" json:"Objects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DBD) Reset()         { *m = DBD{} }
func (m *DBD) String() string { return proto.CompactTextString(m) }
func (*DBD) ProtoMessage()    {}
func (*DBD) Descriptor() ([]byte, []int) {
	return fileDescriptor_db_e304bff5af2f6b9f, []int{2}
}
func (m *DBD) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBD.Unmarshal(m, b)
}
func (m *DBD) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBD.Marshal(b, m, deterministic)
}
func (dst *DBD) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBD.Merge(dst, src)
}
func (m *DBD) XXX_Size() int {
	return xxx_messageInfo_DBD.Size(m)
}
func (m *DBD) XXX_DiscardUnknown() {
	xxx_messageInfo_DBD.DiscardUnknown(m)
}

var xxx_messageInfo_DBD proto.InternalMessageInfo

func (m *DBD) GetReplyID() string {
	if m != nil {
		return m.ReplyID
	}
	return ""
}

func (m *DBD) GetObjects() []*DBObject {
	if m != nil {
		return m.Objects
	}
	return nil
}

type DBUpdate struct {
	Objects              []*DBObject `protobuf:"bytes,1,rep,name=Objects,proto3" json:"Objects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DBUpdate) Reset()         { *m = DBUpdate{} }
func (m *DBUpdate) String() string { return proto.CompactTextString(m) }
func (*DBUpdate) ProtoMessage()    {}
func (*DBUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_db_e304bff5af2f6b9f, []int{3}
}
func (m *DBUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBUpdate.Unmarshal(m, b)
}
func (m *DBUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBUpdate.Marshal(b, m, deterministic)
}
func (dst *DBUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBUpdate.Merge(dst, src)
}
func (m *DBUpdate) XXX_Size() int {
	return xxx_messageInfo_DBUpdate.Size(m)
}
func (m *DBUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_DBUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_DBUpdate proto.InternalMessageInfo

func (m *DBUpdate) GetObjects() []*DBObject {
	if m != nil {
		return m.Objects
	}
	return nil
}

func init() {
	proto.RegisterType((*DBRequest)(nil), "dproto.DBRequest")
	proto.RegisterType((*DBObject)(nil), "dproto.DBObject")
	proto.RegisterType((*DBD)(nil), "dproto.DBD")
	proto.RegisterType((*DBUpdate)(nil), "dproto.DBUpdate")
}

func init() { proto.RegisterFile("dproto/db.proto", fileDescriptor_db_e304bff5af2f6b9f) }

var fileDescriptor_db_e304bff5af2f6b9f = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0x29, 0x28, 0xca,
	0x2f, 0xc9, 0xd7, 0x4f, 0x49, 0xd2, 0x03, 0x33, 0x84, 0xd8, 0x20, 0x02, 0x4a, 0x9a, 0x5c, 0x9c,
	0x2e, 0x4e, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x32, 0x5c, 0x9c, 0x50, 0xa6, 0xa7,
	0x8b, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x42, 0x40, 0x29, 0x8e, 0x8b, 0xc3, 0xc5, 0xc9,
	0x3f, 0x29, 0x2b, 0x35, 0xb9, 0x44, 0x88, 0x8f, 0x8b, 0x09, 0xaa, 0x84, 0x39, 0x88, 0xc9, 0xd3,
	0x45, 0x48, 0x84, 0x8b, 0xd5, 0x31, 0x27, 0xb3, 0x2c, 0x55, 0x82, 0x49, 0x81, 0x51, 0x83, 0x23,
	0x08, 0xc2, 0x11, 0x12, 0xe2, 0x62, 0x71, 0x4c, 0x49, 0x29, 0x92, 0x60, 0x06, 0x1b, 0x05, 0x66,
	0x0b, 0x49, 0x70, 0xb1, 0x07, 0xa5, 0xe6, 0xe6, 0x97, 0xa5, 0xa6, 0x48, 0x70, 0x81, 0xd5, 0xc2,
	0xb8, 0x4a, 0xde, 0x5c, 0xcc, 0x2e, 0x4e, 0x2e, 0x10, 0x05, 0x05, 0x39, 0x95, 0x70, 0x27, 0xc0,
	0xb8, 0x42, 0x5a, 0x5c, 0xec, 0x10, 0xeb, 0x8b, 0x25, 0x98, 0x14, 0x98, 0x35, 0xb8, 0x8d, 0x04,
	0xf4, 0x20, 0xbe, 0xd0, 0x83, 0xb9, 0x2b, 0x08, 0xa6, 0x40, 0xc9, 0x0c, 0xe4, 0xd8, 0xd0, 0x82,
	0x94, 0xc4, 0x92, 0x54, 0x64, 0x7d, 0x8c, 0x04, 0xf4, 0x25, 0xb1, 0x81, 0x25, 0x8c, 0x01, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x20, 0xc9, 0x58, 0x02, 0x31, 0x01, 0x00, 0x00,
}
