// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dproto/db.proto

package dproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Just an empty message.
type DBRequest struct {
	RequestID            string   `protobuf:"bytes,1,opt,name=RequestID,proto3" json:"RequestID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBRequest) Reset()         { *m = DBRequest{} }
func (m *DBRequest) String() string { return proto.CompactTextString(m) }
func (*DBRequest) ProtoMessage()    {}
func (*DBRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db_62a964e2422a9e03, []int{0}
}
func (m *DBRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBRequest.Unmarshal(m, b)
}
func (m *DBRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBRequest.Marshal(b, m, deterministic)
}
func (dst *DBRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBRequest.Merge(dst, src)
}
func (m *DBRequest) XXX_Size() int {
	return xxx_messageInfo_DBRequest.Size(m)
}
func (m *DBRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DBRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DBRequest proto.InternalMessageInfo

func (m *DBRequest) GetRequestID() string {
	if m != nil {
		return m.RequestID
	}
	return ""
}

type PollInterface struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Shortname            string   `protobuf:"bytes,3,opt,name=Shortname,proto3" json:"Shortname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PollInterface) Reset()         { *m = PollInterface{} }
func (m *PollInterface) String() string { return proto.CompactTextString(m) }
func (*PollInterface) ProtoMessage()    {}
func (*PollInterface) Descriptor() ([]byte, []int) {
	return fileDescriptor_db_62a964e2422a9e03, []int{1}
}
func (m *PollInterface) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PollInterface.Unmarshal(m, b)
}
func (m *PollInterface) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PollInterface.Marshal(b, m, deterministic)
}
func (dst *PollInterface) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PollInterface.Merge(dst, src)
}
func (m *PollInterface) XXX_Size() int {
	return xxx_messageInfo_PollInterface.Size(m)
}
func (m *PollInterface) XXX_DiscardUnknown() {
	xxx_messageInfo_PollInterface.DiscardUnknown(m)
}

var xxx_messageInfo_PollInterface proto.InternalMessageInfo

func (m *PollInterface) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *PollInterface) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PollInterface) GetShortname() string {
	if m != nil {
		return m.Shortname
	}
	return ""
}

type DBObject struct {
	ID                   int64            `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Alive                bool             `protobuf:"varint,2,opt,name=Alive,proto3" json:"Alive,omitempty"`
	Addr                 string           `protobuf:"bytes,3,opt,name=Addr,proto3" json:"Addr,omitempty"`
	RoCommunity          string           `protobuf:"bytes,4,opt,name=RoCommunity,proto3" json:"RoCommunity,omitempty"`
	Removed              bool             `protobuf:"varint,10,opt,name=Removed,proto3" json:"Removed,omitempty"`
	PingInterval         int64            `protobuf:"varint,20,opt,name=PingInterval,proto3" json:"PingInterval,omitempty"`
	PollInterval         int64            `protobuf:"varint,21,opt,name=PollInterval,proto3" json:"PollInterval,omitempty"`
	Interfaces           []*PollInterface `protobuf:"bytes,30,rep,name=Interfaces,proto3" json:"Interfaces,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DBObject) Reset()         { *m = DBObject{} }
func (m *DBObject) String() string { return proto.CompactTextString(m) }
func (*DBObject) ProtoMessage()    {}
func (*DBObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_db_62a964e2422a9e03, []int{2}
}
func (m *DBObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBObject.Unmarshal(m, b)
}
func (m *DBObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBObject.Marshal(b, m, deterministic)
}
func (dst *DBObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBObject.Merge(dst, src)
}
func (m *DBObject) XXX_Size() int {
	return xxx_messageInfo_DBObject.Size(m)
}
func (m *DBObject) XXX_DiscardUnknown() {
	xxx_messageInfo_DBObject.DiscardUnknown(m)
}

var xxx_messageInfo_DBObject proto.InternalMessageInfo

func (m *DBObject) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *DBObject) GetAlive() bool {
	if m != nil {
		return m.Alive
	}
	return false
}

func (m *DBObject) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *DBObject) GetRoCommunity() string {
	if m != nil {
		return m.RoCommunity
	}
	return ""
}

func (m *DBObject) GetRemoved() bool {
	if m != nil {
		return m.Removed
	}
	return false
}

func (m *DBObject) GetPingInterval() int64 {
	if m != nil {
		return m.PingInterval
	}
	return 0
}

func (m *DBObject) GetPollInterval() int64 {
	if m != nil {
		return m.PollInterval
	}
	return 0
}

func (m *DBObject) GetInterfaces() []*PollInterface {
	if m != nil {
		return m.Interfaces
	}
	return nil
}

type DBD struct {
	ReplyID              string      `protobuf:"bytes,1,opt,name=ReplyID,proto3" json:"ReplyID,omitempty"`
	Objects              []*DBObject `protobuf:"bytes,2,rep,name=Objects,proto3" json:"Objects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DBD) Reset()         { *m = DBD{} }
func (m *DBD) String() string { return proto.CompactTextString(m) }
func (*DBD) ProtoMessage()    {}
func (*DBD) Descriptor() ([]byte, []int) {
	return fileDescriptor_db_62a964e2422a9e03, []int{3}
}
func (m *DBD) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBD.Unmarshal(m, b)
}
func (m *DBD) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBD.Marshal(b, m, deterministic)
}
func (dst *DBD) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBD.Merge(dst, src)
}
func (m *DBD) XXX_Size() int {
	return xxx_messageInfo_DBD.Size(m)
}
func (m *DBD) XXX_DiscardUnknown() {
	xxx_messageInfo_DBD.DiscardUnknown(m)
}

var xxx_messageInfo_DBD proto.InternalMessageInfo

func (m *DBD) GetReplyID() string {
	if m != nil {
		return m.ReplyID
	}
	return ""
}

func (m *DBD) GetObjects() []*DBObject {
	if m != nil {
		return m.Objects
	}
	return nil
}

type DBUpdate struct {
	Objects              []*DBObject `protobuf:"bytes,1,rep,name=Objects,proto3" json:"Objects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DBUpdate) Reset()         { *m = DBUpdate{} }
func (m *DBUpdate) String() string { return proto.CompactTextString(m) }
func (*DBUpdate) ProtoMessage()    {}
func (*DBUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_db_62a964e2422a9e03, []int{4}
}
func (m *DBUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBUpdate.Unmarshal(m, b)
}
func (m *DBUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBUpdate.Marshal(b, m, deterministic)
}
func (dst *DBUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBUpdate.Merge(dst, src)
}
func (m *DBUpdate) XXX_Size() int {
	return xxx_messageInfo_DBUpdate.Size(m)
}
func (m *DBUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_DBUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_DBUpdate proto.InternalMessageInfo

func (m *DBUpdate) GetObjects() []*DBObject {
	if m != nil {
		return m.Objects
	}
	return nil
}

func init() {
	proto.RegisterType((*DBRequest)(nil), "dproto.DBRequest")
	proto.RegisterType((*PollInterface)(nil), "dproto.PollInterface")
	proto.RegisterType((*DBObject)(nil), "dproto.DBObject")
	proto.RegisterType((*DBD)(nil), "dproto.DBD")
	proto.RegisterType((*DBUpdate)(nil), "dproto.DBUpdate")
}

func init() { proto.RegisterFile("dproto/db.proto", fileDescriptor_db_62a964e2422a9e03) }

var fileDescriptor_db_62a964e2422a9e03 = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xcd, 0x4e, 0xc3, 0x30,
	0x10, 0x84, 0x95, 0xa4, 0xf4, 0x67, 0xcb, 0x9f, 0xac, 0x56, 0xf2, 0x01, 0xa1, 0xca, 0xa7, 0xc2,
	0x21, 0x48, 0x20, 0xb8, 0x37, 0xf8, 0x12, 0x21, 0x41, 0x31, 0xe2, 0x01, 0x92, 0xda, 0x40, 0x50,
	0x12, 0x87, 0xc4, 0x8d, 0xd4, 0xa7, 0x07, 0xc5, 0x8e, 0x43, 0x2a, 0x0e, 0xdc, 0x76, 0x67, 0x67,
	0x3f, 0x7b, 0x07, 0x4e, 0x78, 0x51, 0x4a, 0x25, 0xaf, 0x78, 0xec, 0xeb, 0x02, 0x0d, 0x8d, 0x40,
	0x2e, 0x60, 0x42, 0x03, 0x26, 0xbe, 0xb6, 0xa2, 0x52, 0xe8, 0x0c, 0x26, 0x6d, 0x19, 0x52, 0xec,
	0x2c, 0x9c, 0xe5, 0x84, 0xfd, 0x0a, 0xe4, 0x19, 0x8e, 0xd6, 0x32, 0x4d, 0xc3, 0x5c, 0x89, 0xf2,
	0x2d, 0xda, 0x08, 0x74, 0x0c, 0x6e, 0xeb, 0xf3, 0x98, 0x1b, 0x52, 0x84, 0x60, 0xf0, 0x18, 0x65,
	0x02, 0xbb, 0x7a, 0x53, 0xd7, 0x0d, 0xf2, 0xe5, 0x43, 0x96, 0x2a, 0x6f, 0x06, 0x9e, 0x41, 0x76,
	0x02, 0xf9, 0x76, 0x60, 0x4c, 0x83, 0xa7, 0xf8, 0x53, 0x6c, 0xd4, 0x1f, 0xdc, 0x0c, 0x0e, 0x56,
	0x69, 0x52, 0x1b, 0xde, 0x98, 0x99, 0xa6, 0x79, 0x64, 0xc5, 0x79, 0xd9, 0xb2, 0x74, 0x8d, 0x16,
	0x30, 0x65, 0xf2, 0x5e, 0x66, 0xd9, 0x36, 0x4f, 0xd4, 0x0e, 0x0f, 0xf4, 0xa8, 0x2f, 0x21, 0x0c,
	0x23, 0x26, 0x32, 0x59, 0x0b, 0x8e, 0x41, 0xd3, 0x6c, 0x8b, 0x08, 0x1c, 0xae, 0x93, 0xfc, 0x5d,
	0x5f, 0x55, 0x47, 0x29, 0x9e, 0xe9, 0xf7, 0xf7, 0x34, 0xed, 0xb1, 0x97, 0x37, 0x9e, 0x79, 0xeb,
	0xe9, 0x69, 0xe8, 0x16, 0xa0, 0x4b, 0xa6, 0xc2, 0xe7, 0x0b, 0x6f, 0x39, 0xbd, 0x9e, 0xfb, 0x26,
	0x65, 0x7f, 0x2f, 0x37, 0xd6, 0x33, 0x92, 0x07, 0xf0, 0x68, 0x40, 0xcd, 0xff, 0x8a, 0x74, 0xd7,
	0xe5, 0x6e, 0x5b, 0x74, 0x09, 0x23, 0x93, 0x4f, 0x85, 0x5d, 0x0d, 0x3d, 0xb5, 0x50, 0x1b, 0x1c,
	0xb3, 0x06, 0x72, 0xd7, 0xa4, 0xf9, 0x5a, 0xf0, 0x48, 0x89, 0xfe, 0x9e, 0xf3, 0xcf, 0x5e, 0x3c,
	0xd4, 0x83, 0x9b, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7c, 0x30, 0xa1, 0xf2, 0x26, 0x02, 0x00,
	0x00,
}
