// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dproto/packet.proto

package dproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DPacket struct {
	PacketType           PacketType `protobuf:"varint,1,opt,name=PacketType,proto3,enum=dproto.PacketType" json:"PacketType,omitempty"`
	Payload              *any.Any   `protobuf:"bytes,2,opt,name=Payload,proto3" json:"Payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DPacket) Reset()         { *m = DPacket{} }
func (m *DPacket) String() string { return proto.CompactTextString(m) }
func (*DPacket) ProtoMessage()    {}
func (*DPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_packet_af2e8d53aa9f67da, []int{0}
}
func (m *DPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DPacket.Unmarshal(m, b)
}
func (m *DPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DPacket.Marshal(b, m, deterministic)
}
func (dst *DPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DPacket.Merge(dst, src)
}
func (m *DPacket) XXX_Size() int {
	return xxx_messageInfo_DPacket.Size(m)
}
func (m *DPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_DPacket.DiscardUnknown(m)
}

var xxx_messageInfo_DPacket proto.InternalMessageInfo

func (m *DPacket) GetPacketType() PacketType {
	if m != nil {
		return m.PacketType
	}
	return PacketType_ERROR
}

func (m *DPacket) GetPayload() *any.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*DPacket)(nil), "dproto.DPacket")
}

func init() { proto.RegisterFile("dproto/packet.proto", fileDescriptor_packet_af2e8d53aa9f67da) }

var fileDescriptor_packet_af2e8d53aa9f67da = []byte{
	// 148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0x29, 0x28, 0xca,
	0x2f, 0xc9, 0xd7, 0x2f, 0x48, 0x4c, 0xce, 0x4e, 0x2d, 0xd1, 0x03, 0x73, 0x84, 0xd8, 0x20, 0x82,
	0x52, 0x92, 0xe9, 0xf9, 0xf9, 0xe9, 0x39, 0xa9, 0xfa, 0x60, 0x5e, 0x52, 0x69, 0x9a, 0x7e, 0x62,
	0x5e, 0xa5, 0x1e, 0x54, 0x0a, 0x45, 0x5f, 0x7c, 0x49, 0x65, 0x41, 0x6a, 0x31, 0x44, 0x4a, 0x29,
	0x97, 0x8b, 0xdd, 0x25, 0x00, 0x2c, 0x2c, 0x64, 0xc4, 0xc5, 0x05, 0x61, 0x85, 0x54, 0x16, 0xa4,
	0x4a, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x19, 0x09, 0xe9, 0x41, 0xb4, 0xea, 0x21, 0x64, 0x82, 0x90,
	0x54, 0x09, 0xe9, 0x71, 0xb1, 0x07, 0x24, 0x56, 0xe6, 0xe4, 0x27, 0xa6, 0x48, 0x30, 0x29, 0x30,
	0x6a, 0x70, 0x1b, 0x89, 0xe8, 0x41, 0x9c, 0xa1, 0x07, 0x73, 0x86, 0x9e, 0x63, 0x5e, 0x65, 0x10,
	0x4c, 0x51, 0x12, 0x1b, 0x58, 0xd8, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x1c, 0xe1, 0x1a, 0xdb,
	0xca, 0x00, 0x00, 0x00,
}
