// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dproto/pingupdate.proto

package dproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Pingupdate struct {
	OID                  int64                `protobuf:"varint,1,opt,name=OID,proto3" json:"OID,omitempty"`
	Alive                bool                 `protobuf:"varint,2,opt,name=Alive,proto3" json:"Alive,omitempty"`
	Updated              *timestamp.Timestamp `protobuf:"bytes,3,opt,name=Updated,proto3" json:"Updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Pingupdate) Reset()         { *m = Pingupdate{} }
func (m *Pingupdate) String() string { return proto.CompactTextString(m) }
func (*Pingupdate) ProtoMessage()    {}
func (*Pingupdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_pingupdate_86140472d7a5165d, []int{0}
}
func (m *Pingupdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pingupdate.Unmarshal(m, b)
}
func (m *Pingupdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pingupdate.Marshal(b, m, deterministic)
}
func (dst *Pingupdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pingupdate.Merge(dst, src)
}
func (m *Pingupdate) XXX_Size() int {
	return xxx_messageInfo_Pingupdate.Size(m)
}
func (m *Pingupdate) XXX_DiscardUnknown() {
	xxx_messageInfo_Pingupdate.DiscardUnknown(m)
}

var xxx_messageInfo_Pingupdate proto.InternalMessageInfo

func (m *Pingupdate) GetOID() int64 {
	if m != nil {
		return m.OID
	}
	return 0
}

func (m *Pingupdate) GetAlive() bool {
	if m != nil {
		return m.Alive
	}
	return false
}

func (m *Pingupdate) GetUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.Updated
	}
	return nil
}

func init() {
	proto.RegisterType((*Pingupdate)(nil), "dproto.Pingupdate")
}

func init() { proto.RegisterFile("dproto/pingupdate.proto", fileDescriptor_pingupdate_86140472d7a5165d) }

var fileDescriptor_pingupdate_86140472d7a5165d = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4f, 0x29, 0x28, 0xca,
	0x2f, 0xc9, 0xd7, 0x2f, 0xc8, 0xcc, 0x4b, 0x2f, 0x2d, 0x48, 0x49, 0x2c, 0x49, 0xd5, 0x03, 0x0b,
	0x08, 0xb1, 0x41, 0x24, 0xa4, 0xe4, 0xd3, 0xf3, 0xf3, 0xd3, 0x73, 0x52, 0xf5, 0xc1, 0xbc, 0xa4,
	0xd2, 0x34, 0xfd, 0x92, 0xcc, 0xdc, 0xd4, 0xe2, 0x92, 0xc4, 0xdc, 0x02, 0x88, 0x42, 0xa5, 0x2c,
	0x2e, 0xae, 0x00, 0xb8, 0x66, 0x21, 0x01, 0x2e, 0x66, 0x7f, 0x4f, 0x17, 0x09, 0x46, 0x05, 0x46,
	0x0d, 0xe6, 0x20, 0x10, 0x53, 0x48, 0x84, 0x8b, 0xd5, 0x31, 0x27, 0xb3, 0x2c, 0x55, 0x82, 0x49,
	0x81, 0x51, 0x83, 0x23, 0x08, 0xc2, 0x11, 0x32, 0xe1, 0x62, 0x0f, 0x05, 0xeb, 0x48, 0x91, 0x60,
	0x56, 0x60, 0xd4, 0xe0, 0x36, 0x92, 0xd2, 0x83, 0x58, 0xa4, 0x07, 0xb3, 0x48, 0x2f, 0x04, 0x66,
	0x51, 0x10, 0x4c, 0x69, 0x12, 0x1b, 0x58, 0xd2, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xf0, 0xb1,
	0x68, 0x1f, 0xb6, 0x00, 0x00, 0x00,
}
