// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dproto/types.proto

package dproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TaskType int32

const (
	TaskType_PLATFORM   TaskType = 0
	TaskType_INTERFACES TaskType = 10
	TaskType_LLDP       TaskType = 20
	TaskType_VLANS      TaskType = 30
	TaskType_IPS        TaskType = 40
	TaskType_UPLINK     TaskType = 50
	TaskType_CONFIG     TaskType = 60
)

var TaskType_name = map[int32]string{
	0:  "PLATFORM",
	10: "INTERFACES",
	20: "LLDP",
	30: "VLANS",
	40: "IPS",
	50: "UPLINK",
	60: "CONFIG",
}
var TaskType_value = map[string]int32{
	"PLATFORM":   0,
	"INTERFACES": 10,
	"LLDP":       20,
	"VLANS":      30,
	"IPS":        40,
	"UPLINK":     50,
	"CONFIG":     60,
}

func (x TaskType) String() string {
	return proto.EnumName(TaskType_name, int32(x))
}
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_types_9dfe6897851bde59, []int{0}
}

type ResponseType int32

const (
	ResponseType_Error ResponseType = 0
)

var ResponseType_name = map[int32]string{
	0: "Error",
}
var ResponseType_value = map[string]int32{
	"Error": 0,
}

func (x ResponseType) String() string {
	return proto.EnumName(ResponseType_name, int32(x))
}
func (ResponseType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_types_9dfe6897851bde59, []int{1}
}

type ProfileType int32

const (
	ProfileType_DXS      ProfileType = 0
	ProfileType_DGS3100  ProfileType = 10
	ProfileType_IOS      ProfileType = 20
	ProfileType_JUNOS    ProfileType = 30
	ProfileType_MES      ProfileType = 40
	ProfileType_HUA      ProfileType = 50
	ProfileType_ROUTEROS ProfileType = 60
)

var ProfileType_name = map[int32]string{
	0:  "DXS",
	10: "DGS3100",
	20: "IOS",
	30: "JUNOS",
	40: "MES",
	50: "HUA",
	60: "ROUTEROS",
}
var ProfileType_value = map[string]int32{
	"DXS":      0,
	"DGS3100":  10,
	"IOS":      20,
	"JUNOS":    30,
	"MES":      40,
	"HUA":      50,
	"ROUTEROS": 60,
}

func (x ProfileType) String() string {
	return proto.EnumName(ProfileType_name, int32(x))
}
func (ProfileType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_types_9dfe6897851bde59, []int{2}
}

type Protocol int32

const (
	Protocol_NONE   Protocol = 0
	Protocol_TELNET Protocol = 1
	Protocol_SSH    Protocol = 2
)

var Protocol_name = map[int32]string{
	0: "NONE",
	1: "TELNET",
	2: "SSH",
}
var Protocol_value = map[string]int32{
	"NONE":   0,
	"TELNET": 1,
	"SSH":    2,
}

func (x Protocol) String() string {
	return proto.EnumName(Protocol_name, int32(x))
}
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_types_9dfe6897851bde59, []int{3}
}

type InterfaceType int32

const (
	InterfaceType_UNKNOWN    InterfaceType = 0
	InterfaceType_PHISYCAL   InterfaceType = 1
	InterfaceType_AGGREGATED InterfaceType = 2
	InterfaceType_SVI        InterfaceType = 3
	InterfaceType_TUNNEL     InterfaceType = 4
	InterfaceType_LOOPBACK   InterfaceType = 5
	InterfaceType_MANAGEMENT InterfaceType = 6
	InterfaceType_NULL       InterfaceType = 7
)

var InterfaceType_name = map[int32]string{
	0: "UNKNOWN",
	1: "PHISYCAL",
	2: "AGGREGATED",
	3: "SVI",
	4: "TUNNEL",
	5: "LOOPBACK",
	6: "MANAGEMENT",
	7: "NULL",
}
var InterfaceType_value = map[string]int32{
	"UNKNOWN":    0,
	"PHISYCAL":   1,
	"AGGREGATED": 2,
	"SVI":        3,
	"TUNNEL":     4,
	"LOOPBACK":   5,
	"MANAGEMENT": 6,
	"NULL":       7,
}

func (x InterfaceType) String() string {
	return proto.EnumName(InterfaceType_name, int32(x))
}
func (InterfaceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_types_9dfe6897851bde59, []int{4}
}

func init() {
	proto.RegisterEnum("dproto.TaskType", TaskType_name, TaskType_value)
	proto.RegisterEnum("dproto.ResponseType", ResponseType_name, ResponseType_value)
	proto.RegisterEnum("dproto.ProfileType", ProfileType_name, ProfileType_value)
	proto.RegisterEnum("dproto.Protocol", Protocol_name, Protocol_value)
	proto.RegisterEnum("dproto.InterfaceType", InterfaceType_name, InterfaceType_value)
}

func init() { proto.RegisterFile("dproto/types.proto", fileDescriptor_types_9dfe6897851bde59) }

var fileDescriptor_types_9dfe6897851bde59 = []byte{
	// 334 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x2c, 0x90, 0x41, 0x6f, 0xe2, 0x30,
	0x10, 0x85, 0x03, 0x81, 0x24, 0x0c, 0xec, 0x6a, 0x64, 0xed, 0x65, 0x2f, 0x7b, 0xde, 0xcd, 0x61,
	0x4b, 0xe1, 0xca, 0xc5, 0x4d, 0x4c, 0x48, 0x71, 0xec, 0x28, 0x76, 0xa0, 0xbd, 0x54, 0xa2, 0x34,
	0x48, 0x55, 0x11, 0x89, 0x12, 0xa4, 0x8a, 0x7f, 0x5f, 0xd9, 0xe9, 0x6d, 0x64, 0xeb, 0xcd, 0xf7,
	0xcd, 0x03, 0xf2, 0xd6, 0xb4, 0xf5, 0xb5, 0xbe, 0xbb, 0xde, 0x9a, 0xaa, 0xfb, 0x6f, 0x67, 0xe2,
	0xf5, 0x6f, 0xe1, 0x0b, 0x04, 0xfa, 0xd0, 0x7d, 0xe8, 0x5b, 0x53, 0x91, 0x19, 0x04, 0x39, 0xa7,
	0x7a, 0x2d, 0x8b, 0x0c, 0x1d, 0xf2, 0x13, 0x20, 0x15, 0x9a, 0x15, 0x6b, 0x1a, 0x31, 0x85, 0x40,
	0x02, 0x18, 0x71, 0x1e, 0xe7, 0xf8, 0x8b, 0x4c, 0x60, 0xbc, 0xe3, 0x54, 0x28, 0xfc, 0x43, 0x7c,
	0x70, 0xd3, 0x5c, 0xe1, 0x5f, 0x02, 0xe0, 0x95, 0x39, 0x4f, 0xc5, 0x16, 0x17, 0x66, 0x8e, 0xa4,
	0x58, 0xa7, 0x09, 0xae, 0xc2, 0xdf, 0x30, 0x2b, 0xaa, 0xae, 0xa9, 0x2f, 0x5d, 0x65, 0x19, 0x13,
	0x18, 0xb3, 0xb6, 0xad, 0x5b, 0x74, 0xc2, 0x3d, 0x4c, 0xf3, 0xb6, 0x3e, 0xbd, 0x9f, 0xfb, 0x1f,
	0x1f, 0xdc, 0xf8, 0x49, 0xa1, 0x43, 0xa6, 0xe0, 0xc7, 0x89, 0x5a, 0xde, 0xcf, 0xe7, 0x08, 0x16,
	0x20, 0x55, 0x0f, 0x7d, 0x2c, 0x85, 0xfc, 0x86, 0x66, 0xcc, 0x40, 0x7d, 0x70, 0x37, 0x25, 0xc5,
	0x85, 0x31, 0x2f, 0x64, 0xa9, 0x59, 0x21, 0x15, 0xae, 0xc2, 0x7f, 0x10, 0xe4, 0xe6, 0xb8, 0x63,
	0x7d, 0x36, 0xd6, 0x42, 0x0a, 0x86, 0x8e, 0xb1, 0xd2, 0x8c, 0x0b, 0xa6, 0x71, 0x60, 0x82, 0x4a,
	0x6d, 0x70, 0x18, 0x7e, 0xc2, 0x8f, 0xf4, 0x72, 0xad, 0xda, 0xd3, 0xe1, 0xd8, 0x5b, 0x4c, 0xc1,
	0x2f, 0xc5, 0x56, 0xc8, 0xbd, 0x40, 0xc7, 0x16, 0xb2, 0x49, 0xd5, 0x73, 0x44, 0x39, 0x0e, 0x4c,
	0x21, 0x34, 0x49, 0x0a, 0x96, 0x50, 0xcd, 0x62, 0x1c, 0xda, 0x25, 0xbb, 0x14, 0x5d, 0xbb, 0xb9,
	0x14, 0x82, 0x71, 0x1c, 0x99, 0x08, 0x97, 0x32, 0x7f, 0xa0, 0xd1, 0x16, 0xc7, 0x26, 0x92, 0x51,
	0x41, 0x13, 0x96, 0x31, 0xa1, 0xd1, 0xb3, 0x36, 0x25, 0xe7, 0xe8, 0xbf, 0x7a, 0xb6, 0xfe, 0xe5,
	0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5f, 0x51, 0x89, 0xa9, 0x9c, 0x01, 0x00, 0x00,
}
