// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dproto/types.proto

package dproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TaskType int32

const (
	TaskType_PLATFORM   TaskType = 0
	TaskType_INTERFACES TaskType = 10
	TaskType_LLDP       TaskType = 20
	TaskType_VLANS      TaskType = 30
	TaskType_IPS        TaskType = 40
	TaskType_UPLINK     TaskType = 50
	TaskType_CONFIG     TaskType = 60
)

var TaskType_name = map[int32]string{
	0:  "PLATFORM",
	10: "INTERFACES",
	20: "LLDP",
	30: "VLANS",
	40: "IPS",
	50: "UPLINK",
	60: "CONFIG",
}
var TaskType_value = map[string]int32{
	"PLATFORM":   0,
	"INTERFACES": 10,
	"LLDP":       20,
	"VLANS":      30,
	"IPS":        40,
	"UPLINK":     50,
	"CONFIG":     60,
}

func (x TaskType) String() string {
	return proto.EnumName(TaskType_name, int32(x))
}
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_types_d6003d89c08944b2, []int{0}
}

type ResponseType int32

const (
	ResponseType_Error ResponseType = 0
)

var ResponseType_name = map[int32]string{
	0: "Error",
}
var ResponseType_value = map[string]int32{
	"Error": 0,
}

func (x ResponseType) String() string {
	return proto.EnumName(ResponseType_name, int32(x))
}
func (ResponseType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_types_d6003d89c08944b2, []int{1}
}

type ProfileType int32

const (
	ProfileType_DXS      ProfileType = 0
	ProfileType_DGS3100  ProfileType = 10
	ProfileType_IOS      ProfileType = 20
	ProfileType_JUNOS    ProfileType = 30
	ProfileType_MES      ProfileType = 40
	ProfileType_HUA      ProfileType = 50
	ProfileType_ROUTEROS ProfileType = 60
	ProfileType_QTECH    ProfileType = 70
)

var ProfileType_name = map[int32]string{
	0:  "DXS",
	10: "DGS3100",
	20: "IOS",
	30: "JUNOS",
	40: "MES",
	50: "HUA",
	60: "ROUTEROS",
	70: "QTECH",
}
var ProfileType_value = map[string]int32{
	"DXS":      0,
	"DGS3100":  10,
	"IOS":      20,
	"JUNOS":    30,
	"MES":      40,
	"HUA":      50,
	"ROUTEROS": 60,
	"QTECH":    70,
}

func (x ProfileType) String() string {
	return proto.EnumName(ProfileType_name, int32(x))
}
func (ProfileType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_types_d6003d89c08944b2, []int{2}
}

type Protocol int32

const (
	Protocol_NONE   Protocol = 0
	Protocol_TELNET Protocol = 1
	Protocol_SSH    Protocol = 2
)

var Protocol_name = map[int32]string{
	0: "NONE",
	1: "TELNET",
	2: "SSH",
}
var Protocol_value = map[string]int32{
	"NONE":   0,
	"TELNET": 1,
	"SSH":    2,
}

func (x Protocol) String() string {
	return proto.EnumName(Protocol_name, int32(x))
}
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_types_d6003d89c08944b2, []int{3}
}

type InterfaceType int32

const (
	InterfaceType_UNKNOWN    InterfaceType = 0
	InterfaceType_PHISYCAL   InterfaceType = 1
	InterfaceType_AGGREGATED InterfaceType = 2
	InterfaceType_SVI        InterfaceType = 3
	InterfaceType_TUNNEL     InterfaceType = 4
	InterfaceType_LOOPBACK   InterfaceType = 5
	InterfaceType_MANAGEMENT InterfaceType = 6
	InterfaceType_NULL       InterfaceType = 7
)

var InterfaceType_name = map[int32]string{
	0: "UNKNOWN",
	1: "PHISYCAL",
	2: "AGGREGATED",
	3: "SVI",
	4: "TUNNEL",
	5: "LOOPBACK",
	6: "MANAGEMENT",
	7: "NULL",
}
var InterfaceType_value = map[string]int32{
	"UNKNOWN":    0,
	"PHISYCAL":   1,
	"AGGREGATED": 2,
	"SVI":        3,
	"TUNNEL":     4,
	"LOOPBACK":   5,
	"MANAGEMENT": 6,
	"NULL":       7,
}

func (x InterfaceType) String() string {
	return proto.EnumName(InterfaceType_name, int32(x))
}
func (InterfaceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_types_d6003d89c08944b2, []int{4}
}

type DiscoveryProblem int32

const (
	DiscoveryProblem_NO_NEIGHBORS DiscoveryProblem = 0
	DiscoveryProblem_NO_UPLINK    DiscoveryProblem = 10
	DiscoveryProblem_NO_VLANS     DiscoveryProblem = 20
)

var DiscoveryProblem_name = map[int32]string{
	0:  "NO_NEIGHBORS",
	10: "NO_UPLINK",
	20: "NO_VLANS",
}
var DiscoveryProblem_value = map[string]int32{
	"NO_NEIGHBORS": 0,
	"NO_UPLINK":    10,
	"NO_VLANS":     20,
}

func (x DiscoveryProblem) String() string {
	return proto.EnumName(DiscoveryProblem_name, int32(x))
}
func (DiscoveryProblem) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_types_d6003d89c08944b2, []int{5}
}

func init() {
	proto.RegisterEnum("dproto.TaskType", TaskType_name, TaskType_value)
	proto.RegisterEnum("dproto.ResponseType", ResponseType_name, ResponseType_value)
	proto.RegisterEnum("dproto.ProfileType", ProfileType_name, ProfileType_value)
	proto.RegisterEnum("dproto.Protocol", Protocol_name, Protocol_value)
	proto.RegisterEnum("dproto.InterfaceType", InterfaceType_name, InterfaceType_value)
	proto.RegisterEnum("dproto.DiscoveryProblem", DiscoveryProblem_name, DiscoveryProblem_value)
}

func init() { proto.RegisterFile("dproto/types.proto", fileDescriptor_types_d6003d89c08944b2) }

var fileDescriptor_types_d6003d89c08944b2 = []byte{
	// 386 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x2c, 0x91, 0x41, 0x73, 0xd3, 0x30,
	0x10, 0x85, 0xdd, 0xa6, 0x89, 0x93, 0x4d, 0xca, 0xec, 0x68, 0x7a, 0xe1, 0xc2, 0x19, 0x7c, 0x80,
	0xd2, 0x5e, 0x7b, 0x51, 0x6d, 0xc5, 0x36, 0x51, 0x56, 0xc2, 0x92, 0x0b, 0x5c, 0xc8, 0x34, 0xc1,
	0x9d, 0xe9, 0x10, 0xaa, 0x8c, 0x9c, 0x81, 0xc9, 0xbf, 0x67, 0x24, 0xf7, 0xb6, 0x23, 0xed, 0xbe,
	0xef, 0xed, 0x5b, 0x60, 0xbf, 0x0e, 0xde, 0x1d, 0xdd, 0xa7, 0xe3, 0xe9, 0xd0, 0xf5, 0x1f, 0x63,
	0xcd, 0x26, 0xc3, 0x5b, 0xf6, 0x13, 0xa6, 0xf6, 0xb1, 0xff, 0x6d, 0x4f, 0x87, 0x8e, 0x2d, 0x60,
	0xaa, 0x25, 0xb7, 0x4b, 0xd5, 0xac, 0x31, 0x61, 0x6f, 0x00, 0x6a, 0xb2, 0xa2, 0x59, 0xf2, 0x5c,
	0x18, 0x04, 0x36, 0x85, 0x0b, 0x29, 0x0b, 0x8d, 0x57, 0x6c, 0x06, 0xe3, 0x07, 0xc9, 0xc9, 0xe0,
	0x3b, 0x96, 0xc2, 0xa8, 0xd6, 0x06, 0xdf, 0x33, 0x80, 0x49, 0xab, 0x65, 0x4d, 0x2b, 0xbc, 0x09,
	0x75, 0xae, 0x68, 0x59, 0x97, 0x78, 0x97, 0xbd, 0x85, 0x45, 0xd3, 0xf5, 0x07, 0xf7, 0xd2, 0x77,
	0x91, 0x31, 0x83, 0xb1, 0xf0, 0xde, 0x79, 0x4c, 0xb2, 0x2d, 0xcc, 0xb5, 0x77, 0x4f, 0xcf, 0xfb,
	0xe1, 0x27, 0x85, 0x51, 0xf1, 0xdd, 0x60, 0xc2, 0xe6, 0x90, 0x16, 0xa5, 0xb9, 0xfd, 0x7c, 0x7d,
	0x8d, 0x10, 0x01, 0xca, 0x0c, 0xd0, 0x2f, 0x2d, 0xa9, 0x57, 0xe8, 0x5a, 0x04, 0x68, 0x0a, 0xa3,
	0xaa, 0xe5, 0x78, 0x13, 0x9c, 0x37, 0xaa, 0xb5, 0xa2, 0x51, 0x06, 0xef, 0x42, 0xeb, 0x57, 0x2b,
	0xf2, 0x0a, 0x97, 0xd9, 0x07, 0x98, 0xea, 0xb0, 0xe7, 0xce, 0xed, 0xc3, 0x02, 0xa4, 0x48, 0x60,
	0x12, 0x0c, 0x5a, 0x21, 0x49, 0x58, 0x3c, 0x0b, 0x1a, 0xc6, 0x54, 0x78, 0x9e, 0xfd, 0x83, 0xcb,
	0xfa, 0xe5, 0xd8, 0xf9, 0xa7, 0xc7, 0xdd, 0x60, 0x68, 0x0e, 0x69, 0x4b, 0x2b, 0x52, 0xdf, 0x08,
	0x93, 0x98, 0x4d, 0x55, 0x9b, 0x1f, 0x39, 0x97, 0x78, 0x16, 0xb2, 0xe1, 0x65, 0xd9, 0x88, 0x92,
	0x5b, 0x51, 0xe0, 0x79, 0x14, 0x79, 0xa8, 0x71, 0x14, 0x95, 0x5b, 0x22, 0x21, 0xf1, 0x22, 0x8c,
	0x48, 0xa5, 0xf4, 0x3d, 0xcf, 0x57, 0x38, 0x0e, 0x23, 0x6b, 0x4e, 0xbc, 0x14, 0x6b, 0x41, 0x16,
	0x27, 0xd1, 0x4d, 0x2b, 0x25, 0xa6, 0x19, 0x07, 0x2c, 0x9e, 0xfb, 0x9d, 0xfb, 0xdb, 0xf9, 0x93,
	0xf6, 0x6e, 0xbb, 0xef, 0xfe, 0x30, 0x84, 0x05, 0xa9, 0x0d, 0x89, 0xba, 0xac, 0xee, 0x55, 0x13,
	0x52, 0xb9, 0x84, 0x19, 0xa9, 0xcd, 0x6b, 0xc6, 0x10, 0xc4, 0x49, 0x6d, 0x86, 0x33, 0x5c, 0x6d,
	0x27, 0xf1, 0x98, 0xb7, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x02, 0x1f, 0x8a, 0x3b, 0xea, 0x01,
	0x00, 0x00,
}
